### ISSUE TITLE
${URL}/.well-known/host-meta is not reachable

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#79]
With my current docker-setup, I get an error at the admin overview page because /.well-known/host-meta isn't reachable.

![Screenshot_2019-09-10 Philipp's Friendica Admin](https://user-images.githubusercontent.com/379654/64613206-e7163d80-d3d5-11e9-819d-182cf39b37a3.png)

My current docker-compose is:
```yml
   app:
    image: friendica/server:rc-fpm-alpine
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - db
      - redis
    volumes:
     - friendica-vol-1:/var/www/html
    environment:
      - MYSQL_USERNAME=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=${DBDATA}
      - MYSQL_HOST=${DBHOST}
      - MYSQL_PORT=${DBPORT}
      - FRIENDICA_ADMIN_MAIL=${MAILNAME}
      - FRIENDICA_TZ=${TZ}
      - FRIENDICA_LANG=${LANGUAGE}
      - FRIENDICA_UPGRADE=true
      - REDIS_HOST=redis
      - FRIENDICA_DATA=true
      - FRIENDICA_DEBUGGING=true
      - SMTP=mail
      - SITENAME=${SITENAME}
    restart: always
    networks:
      default:
        aliases:
          - app
      private:
        aliases:
          - friendica_web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: ./web
    restart: always
    volumes:
      - friendica-vol-1:/var/www/html:ro
    environment:
      - HOSTNAME=${HOSTNAME}
    depends_on:
      - app
    networks:
      - web
      - default
    labels:
      - "traefik.backend=friendica"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=15768000"
      - "traefik.frontend.headers.STSIncludeSubdomains=false"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.friendica.frontend.rule=Host:${HOSTNAME}"
      - "traefik.friendica.port=80"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
```

**Comment by commagray** [comment]
Same here. Docker, Traefik, and reverse proxy with Caddy.

![image](https://user-images.githubusercontent.com/27947961/71778011-c0959700-2fb0-11ea-828b-0612df759c7d.png)

But https://derpy.email/.well-known/host-meta is reachable.

**Comment by nupplaphil** [comment]
I found a solution for this issue:
```yml
app:
    image: friendica/server:rc-fpm-alpine
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - db
      - redis
    volumes:
     - friendica-vol-1:/var/www/html
    environment:
      - MYSQL_USERNAME=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=${DBDATA}
      - MYSQL_HOST=${DBHOST}
      - MYSQL_PORT=${DBPORT}
      - FRIENDICA_ADMIN_MAIL=${MAILNAME}
      - FRIENDICA_TZ=${TZ}
      - FRIENDICA_LANG=${LANGUAGE}
      - FRIENDICA_UPGRADE=true
      - REDIS_HOST=redis
      - FRIENDICA_DATA=true
      - FRIENDICA_DEBUGGING=true
      - SMTP=mail
      - SITENAME=${SITENAME}
    restart: always
    extra_hosts:
       - "friendica.philipp.info:172.18.0.2"
       - "opensocial.at:172.18.0.2"
```

`172.18.0.2` is the local IP of the docker gateway. Now a ping of the own hostname will redirect to the gateway and answer inside the local vlan rather than trying to ping ourselfs from the outside.
=> The messages vanished and the Curls to the own hostname now works :)

@commagray can you check it, if this will solve your message too? And if #99 is now working? I've the fear that #99 is not caused by this issue

**Comment by commagray** [comment]
Uhh. I tried these options:

```
    extra_hosts:
      - "derpy.email:192.168.96.3"
      - "derpy.email:172.18.0.3"
      - "derpy.email:172.18.0.2"
      - "derpy.email:172.18.0.13"
```

All of IPs I've seen in `docker inspect`.

Nope, I still have the message.

![image](https://user-images.githubusercontent.com/27947961/71781250-25fb7f00-2fd5-11ea-8a3a-a4a940b2df2d.png)

And I still affected by #99.

**Comment by commagray** [comment]
Some logs?

```
2020-01-05 23:32:01 index [WARNING]: error: https://derpy.email/.well-known/host-meta: 0 - Failed to connect to derpy.email port 443: Connection refused [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;26e8ae&quot;,&quot;process_id&quot;:22956}
2020-01-05 23:32:53 index [WARNING]: error: https://derpy.email/.well-known/host-meta: 0 - Failed to connect to derpy.email port 443: Connection refused [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;84aa99&quot;,&quot;process_id&quot;:22882}
2020-01-05 23:34:18 index [WARNING]: error: https://derpy.email/.well-known/host-meta: 0 - Failed to connect to derpy.email port 443: Connection refused [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;80c32e&quot;,&quot;process_id&quot;:22952}
2020-01-05 23:35:40 index [WARNING]: API call - not implemented {&quot;module&quot;:&quot;api&quot;,&quot;action&quot;:&quot;call&quot;,&quot;query&quot;:&quot;api\/v1\/custom_emojis&quot;} - {&quot;file&quot;:&quot;api.php&quot;,&quot;line&quot;:369,&quot;function&quot;:&quot;api_call&quot;,&quot;uid&quot;:&quot;149226&quot;,&quot;process_id&quot;:22951}
2020-01-05 23:38:44 index [WARNING]: error: https://derpy.email/.well-known/host-meta: 0 - Failed to connect to derpy.email port 443: Connection refused [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;064762&quot;,&quot;process_id&quot;:22956}
2020-01-05 23:38:58 index [NOTICE]: Addon rendertime: install {&quot;action&quot;:&quot;install&quot;,&quot;addon&quot;:&quot;rendertime&quot;} - {&quot;file&quot;:&quot;Addon.php&quot;,&quot;line&quot;:175,&quot;function&quot;:&quot;install&quot;,&quot;uid&quot;:&quot;bfd6a1&quot;,&quot;process_id&quot;:22951}
2020-01-05 23:41:17 worker [WARNING]: error: https://derpy.email/images/person-300.jpg: 0 - Failed to connect to derpy.email port 443: Connection refused {&quot;worker_id&quot;:&quot;86271e0&quot;,&quot;worker_cmd&quot;:&quot;UpdateContact&quot;} - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;3c7c6b&quot;,&quot;process_id&quot;:24233}
2020-01-05 23:41:34 index [NOTICE]: no data for session {&quot;session_id&quot;:&quot;49102274e35ba780041aedd6dd44da5a&quot;,&quot;uri&quot;:&quot;\/robots.txt&quot;} - {&quot;file&quot;:&quot;CacheSessionHandler.php&quot;,&quot;line&quot;:35,&quot;function&quot;:&quot;read&quot;,&quot;uid&quot;:&quot;00e394&quot;,&quot;process_id&quot;:22956}
2020-01-05 23:49:01 index [WARNING]: error: https://mastodon.social/users/jacquespoilu: 410 -  [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;0851f5&quot;,&quot;process_id&quot;:22884}
2020-01-05 23:49:01 index [WARNING]: error: https://mastodon.social/users/jacquespoilu: 410 -  [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;0851f5&quot;,&quot;process_id&quot;:22884}
2020-01-05 23:49:01 index [WARNING]: Invalid HTTP signature, message will be discarded. [] - {&quot;file&quot;:&quot;Receiver.php&quot;,&quot;line&quot;:68,&quot;function&quot;:&quot;processInbox&quot;,&quot;uid&quot;:&quot;0851f5&quot;,&quot;process_id&quot;:22884}
2020-01-05 23:49:31 index [WARNING]: error: https://derpy.email/.well-known/host-meta: 0 - Failed to connect to derpy.email port 443: Connection refused [] - {&quot;file&quot;:&quot;CurlResult.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;checkSuccess&quot;,&quot;uid&quot;:&quot;639c36&quot;,&quot;process_id&quot;:22958}
```

**Comment by commagray** [comment]
Okay, so my solution was absolutely vice versa, lol.

```diff
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=[REDACTED]
      - MYSQL_PASSWORD=[REDACTED]
      - MYSQL_DATABASE=[REDACTED]
      - FRIENDICA_ADMIN_MAIL=[REDACTED]
+     - FRIENDICA_UPGRADE=false
+     - FRIENDICA_SITENAME=derpy.email
+     - SITENAME=derpy.email
-   hostname: derpy.email
+   #hostname: derpy.email
    depends_on:
      - db
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.backend=derpapp
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.frontend.rule=Host:derpy.email
      - com.centurylinklabs.watchtower.enable=true
-   extra_hosts:
-     - "derpy.email:192.168.96.3"
-     - "derpy.email:172.18.0.3"
-     - "derpy.email:172.18.0.2"
-     - "derpy.email:172.18.0.13"
+   #extra_hosts:
+   #  - "derpy.email:192.168.96.3"
+   #  - "derpy.email:172.18.0.3"
+   #  - "derpy.email:172.18.0.2"
+   #  - "derpy.email:172.18.0.13"
```

Seems fixed the message. Still, I need to test my federation with #99.

**Comment by nupplaphil** [comment]
Hmm... Are mails still working with this setup? I guess not.. `Hostname` is used for the smtp setup. So you deleted the `Hostname` parameter and now the instance doesn't know anymore that `derpy.email` is your local container and tries to ping it "again" from the outside..

 But maybe that's a valid solution.. Maybe I "just" have to use another env for the mail host.. Thx for the tests!!

**Comment by commagray** [comment]
I use the “PHP Mailer SMTP” addon, so no issues in my setup.

**Comment by nupplaphil** [comment]
Hmkay.. I think I'll remove the hostname usage, this should fix this issue

**Comment by commagray** [comment]
Now it happens again.

![image](https://user-images.githubusercontent.com/27947961/73026601-6747b780-3e3a-11ea-8073-44d807b645a0.png)

```
root@f267927c8e73:/var/www/html# curl http://localhost/.well-known/host-meta
<html>
        <head>
                <title>Service Unavailable</title>
        </head>
        <body>
                <h1>Service Unavailable</h1>
                <p></p>
        </body>
</html>
```

But if you give it some time it'll be fine again. The worker seems not working?

**Comment by MrPetovan** [comment]
"Service unavailable" means that your server load average has reached the limit Friendica uses to cut any call short. This limit can be configured in the admin panel or via command line.

**Comment by nupplaphil** [comment]
This didn't work as well .. I still have Timeouts when pinging my own node ..

**Comment by iannuzzelli** [comment]
I was having the same issue, and it was solved by adding the extra_hosts section, mind that the gateway IP may change depending on your docker setup (in my case is 172.17.0.1)

**Comment by nupplaphil** [comment]
This is really not a good solution :-/ 

Maybe I can have a look for the root cause and fix it ..

**Comment by nupplaphil** [comment]
I think that this issue isn't "solvable" within the docker image code. It's a general problem with curl/fetching inside the docker network environment .. But I don't have any good idea for a better solution than mapping the gateway IP to the local node hostnames ... So if somebody has a better idea, I will add it to the ".examples" directory as best practice .. meanwhile this issue will stay open until found :-)

**Comment by elrido** [comment]
Not a better idea, but a little extra information nugget: As the internal gateway IP can change, I've instead mapped the sites hostname to the external static IP of the gateway service. This adds a little latency, but won't change without my intervention.

I've got to be honest - I had noticed this message ever since I switched my former installation to this container image. Had ignored it, assuming it was just an internal check. Since the upgrade to 2021.07 I didn't get any ActivityPub updates any more - I suspect this setting is now necessary due to https://github.com/friendica/friendica/pull/10257

**Comment by scifijunk** [comment]
Well, I just hit this problem today. The only thing I changed was updating Nginx Proxy Manager to v2.10.3. It appears that my node still seems to see other nodes and I'm able to follow contacts. I'm also seeing the Message queues going up and down like normal. I'm not sure if people can follow me or see me on their nodes.

I'm kinda at a loss for what to do since on the one hand it looks like it's working as normal and on the other hand I have this error that says it's not.

Update: I think I fixed the problem on my end. It seems it did not like the SSL I set up in Nginx Proxy Manager so I redid it. When I did that the error went away. So maybe check your SSL and make sure it's set right.

**Comment by JohanLeirnes** [comment]
Still having this error.

the addition of binding the fqdn to the gateway address works for getting rid of the message but it does not fix not getting any ActivityPub updates.

Anyone can shine a light on how to fix this?
